[package]
name = "gt-planner-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "gtp"
path = "src/main.rs"

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
gt-planner-core = { workspace = true }
gt-planner-gpu = { path = "../gpu" }
clap = { workspace = true }
serde_json = { workspace = true }
