[package]
name = "gt-planner-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "gt-planner-server"
path = "src/main.rs"

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
gt-planner-core = { workspace = true }
gt-planner-gpu = { path = "../gpu" }
axum = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
